### PR TITLE
Many new calendar features

### PR DESCRIPTION
**Pull request by kewisch**
I've been busy :D

The commits are each pretty small, if you prefer an easier review go commit by commit.

### CODE REVIEW

**Comment by kewisch** [comment]
Please hold, some stuff isn't right.

**Comment by kewisch** [comment]
Merge #35 first, this builds on it. Ready to go otherwise.

**Comment by jobisoft** [comment]
Could you rebase the PR? I will try to review it before Dublin.

**Comment by kewisch** [comment]
No pressure, after Dublin would be fine just as well

**Review by jobisoft — APPROVED** [review]
I went through this line by line and did not see obvious mishaps. I do not have the knowledge about the calendar code to be of real help. I guess we will see issues when this is being used :-)

One thing which I think we talked about already is the `onAdvanceNewCalendar` event. I do not know if the wizard should be part of the API, or if it should be just a content page which can signal "done" by transmitting the settings once the user finished entering the data. This is of course not blocking this PR, maybe just something to keep in mind to re-visit later.

**Comment by kewisch** [comment]
Yes, the onAdvanceNewCalendar thing should be revisited. I'm not completely happy with it. We could just give the whole surface to the add-on after initial steps, they'd still need to signal completion in some way. Let's discuss that later down the line, and as there is more clarity on how a potential new calendar dialog could look like.

**Pull request merged**
